version: 2

sources:
  - name: raw_data
    database: edgered-case-study # Your GCP project ID
    schema: edgered_case_study    # The dataset name
    tables:
      - name: payments     # Table name in BigQuery
        description: "Cleaned payments data loaded into BigQuery"
      - name: clients      # Another raw table if needed
        description: "Cleaned clients data loaded into BigQuery"